### ISSUE TITLE
what's the current status of this repo?

### ISSUE THREAD

**Issue by mydearxym** [maartenvanvliet/absinthe_trace_reporter#10]
hi @maartenvanvliet , this reporter looks great for absinthe project, but it seems not ready for production usage, so what's the roadmap of this project? 

>  .. without having to use a the (deprecated) engine proxy.. 

and if send trace-info directly to apollo-cloud, the cache may not work anymore..

**Comment by maartenvanvliet** [comment]
Yes it's not ready for production usage. I don't know what it's current status is though since I haven't touched it in a while and haven't looked at what happens at the Apollo-cloud side of things. 

It could successfully send traces to Apollo, although some traces were incorrect in the transformation of the tracing data to the protocol buffers Apollo accepts. I didn't get it to work back then and life got in the way :)

I also have no idea if the protocol that's accepted has changed on the Apollo-cloud, and whether it is still useful to work on this since they deprecated the engine proxy.

You are welcome to try it out though.

**Comment by mydearxym** [comment]
@maartenvanvliet  thanks for the explanation, i am still using the deprecated apollo-engine in my project, the new apollo-server has lots of changes and i haven't try it yet.

I will try it at the end of this month.
